# =========================================
# APPLICATION
# =========================================

spring.application.name=incident-management-api

server.port=8080
server.servlet.context-path=/api

# =========================================
# DATASOURCE
# =========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/incidentdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================
# JPA / HIBERNATE
# =========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================================
# H2 CONSOLE
# =========================================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================================
# LOGGING
# =========================================

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.example.incidentmanager=DEBUG

logging.file.name=logs/incident-management.log

# =========================================
# JWT
# =========================================

jwt.secret=mySecretKeyJwtTokenSpringBoot2026
jwt.expiration=3600000
jwt.refresh-expiration=86400000

# =========================================
# SWAGGER / OPENAPI
# =========================================

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# =========================================
# ACTUATOR
# =========================================

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# =========================================
# JACKSON
# =========================================

spring.jackson.serialization.indent-output=true