services:
  - type: web
    name: INCIDENT-TEST
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /api/actuator/health
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: incidentdb
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: incidentdb
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: incidentdb
          property: password
      - key: SPRING_H2_CONSOLE_ENABLED
        value: "false"
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: incidentdb
    plan: free